#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mem=24gb:ngpus=1:gpu_type=RTX6000

module load anaconda3/personal
module load tools/prod
module load MATLAB/2023a_Update_3
module load SciPy-bundle/2023.02-gfbf-2022b

source activate pytorch_env

cd $PBS_O_WORKDIR



python HRTF-upsampling-with-a-generative-adversarial-network-using-a-gnomonic-equiangular-projection-main-with-noise/main.py train with_noise white_noise_-50dB/white_train_-50dB  brown_noise_-50dB/brown_valid_-50dB --hpc True --tag ari-upscale-4-white-negative-50dB --generated_sofa_file_folder_name _white_-50dB --clean_hrtf_ratio 1